'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Bell, CalendarDays, ChevronDown, HeartHandshake, LayoutDashboard, Menu, Search, Settings, ShieldCheck, Users, X } from 'lucide-react'

const sessions = [
  { date: '24', month: 'OCT', title: 'Family thanksgiving meeting', meta: 'Sat, 24 Oct · 4:00 PM', present: 42, total: 48, status: 'Upcoming' },
  { date: '10', month: 'OCT', title: 'Monthly family meeting', meta: 'Sat, 10 Oct · 4:00 PM', present: 44, total: 48, status: 'Recorded' },
  { date: '26', month: 'SEP', title: 'September family meeting', meta: 'Sat, 26 Sep · 4:00 PM', present: 40, total: 48, status: 'Recorded' },
  { date: '12', month: 'SEP', title: 'Family prayer gathering', meta: 'Sat, 12 Sep · 5:00 PM', present: 43, total: 48, status: 'Recorded' },
]

const members = [
  ['Daniel Adeyemi', 'DA', 'Present', '4 of 4'], ['Grace Okafor', 'GO', 'Present', '4 of 4'], ['Michael Eze', 'ME', 'Late', '3 of 4'], ['Esther Adebayo', 'EA', 'Absent', '2 of 4'], ['Ruth Bello', 'RB', 'Present', '4 of 4'],
]

export default function AttendancePage() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [period, setPeriod] = useState('Last 6 months')
  return <div className="min-h-screen bg-[#f4f8fc] text-[#172a46]">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[256px] flex-col bg-[#132745] px-5 py-6 text-white transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between px-2"><Link href="/" className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-[13px] bg-[#8dd6ff] text-[#132745]"><HeartHandshake className="size-5" /></div><div><p className="text-[15px] font-bold tracking-wide">Faithful</p><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[#8da8c8]">Family records</p></div></Link><button aria-label="Close navigation" className="rounded-lg p-2 text-[#a9bfd8] lg:hidden" onClick={() => setMobileOpen(false)}><X /></button></div>
      <nav className="mt-12 flex flex-1 flex-col gap-1.5" aria-label="Main navigation"><p className="px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#7592b4]">Workspace</p><Link href="/" className="nav-link"><LayoutDashboard />Overview</Link><Link href="/roster" className="nav-link"><Users />Family roster</Link><Link href="/meetings" className="nav-link"><CalendarDays />Meetings &amp; minutes</Link><Link href="/attendance" className="nav-link active"><CalendarDays />Attendance</Link><Link href="#contributions" className="nav-link"><ShieldCheck />Contributions</Link><p className="mt-10 px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#7592b4]">Account</p><button className="nav-link"><Settings />Settings</button></nav>
      <div className="rounded-2xl border border-white/10 bg-white/6 p-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-[#d9efff] text-sm font-bold text-[#2764a3]">DA</div><div><p className="text-xs font-semibold">Daniel Adeyemi</p><p className="mt-0.5 text-[11px] text-[#8da8c8]">Member · Dominion</p></div></div></div>
    </aside>
    {mobileOpen && <button aria-label="Close navigation overlay" className="fixed inset-0 z-20 bg-[#0e2039]/40 lg:hidden" onClick={() => setMobileOpen(false)} />}
    <main className="lg:pl-[256px]"><header className="flex h-[76px] items-center justify-between border-b border-[#dce8f3] bg-white/80 px-5 backdrop-blur-xl sm:px-8 lg:px-10"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="rounded-xl p-2 text-[#426487] lg:hidden" onClick={() => setMobileOpen(true)}><Menu /></button><div className="hidden items-center gap-2 text-xs text-[#7690aa] sm:flex"><span>Family workspace</span><span>/</span><span className="font-medium text-[#274463]">Attendance</span></div><span className="text-sm font-semibold text-[#1f3857] sm:hidden">Attendance</span></div><div className="flex items-center gap-2 sm:gap-4"><button aria-label="Search" className="rounded-xl p-2.5 text-[#55718e]"><Search className="size-[19px]" /></button><button aria-label="Notifications" className="relative rounded-xl p-2.5 text-[#55718e]"><Bell className="size-[19px]" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-[#2f8ad8]" /></button><div className="flex size-8 items-center justify-center rounded-full bg-[#d9efff] text-xs font-bold text-[#2764a3]">DA</div></div></header>
      <div className="mx-auto max-w-[1380px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9"><Link href="/" className="inline-flex items-center gap-2 text-xs font-semibold text-[#5f82a2] hover:text-[#2e75c7]"><ArrowLeft className="size-4" />Back to overview</Link><section className="mt-6 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-medium text-[#5d7b99]">Dominion Family</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em] text-[#142e4d] sm:text-[38px]">Attendance <span className="text-[#4295d5]">.</span></h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#7290ad]">See how our family is showing up, staying connected, and growing together.</p></div><button className="flex w-fit items-center gap-2 rounded-xl bg-[#2e75c7] px-4 py-3 text-sm font-semibold text-white shadow-[0_10px_20px_rgba(46,117,199,0.2)]"><CalendarDays className="size-4" />Record attendance</button></section>
      <section className="mt-8 grid gap-4 sm:grid-cols-3"><Summary label="Overall attendance" value="86%" detail="+4.2% from last month" /><Summary label="Average per meeting" value="42 / 48" detail="Members attending" /><Summary label="Meetings recorded" value="18" detail="This year" /></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.8fr)]"><div className="rounded-[22px] border border-[#dce8f3] bg-white p-5 shadow-[0_12px_36px_rgba(49,92,130,0.05)] sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-bold text-[#1a3858]">Attendance trend</h2><p className="mt-1 text-xs text-[#89a0b6]">Family participation over time</p></div><select aria-label="Attendance period" value={period} onChange={(e) => setPeriod(e.target.value)} className="rounded-lg border border-[#dce8f3] bg-white px-2.5 py-2 text-xs font-medium text-[#58738f]"><option>Last 6 months</option><option>This year</option></select></div><div className="mt-7 flex h-[205px] items-end gap-3 border-b border-[#e9f0f6] px-2 sm:gap-6">{[68, 75, 64, 88, 79, 94].map((height, i) => <div key={i} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] font-bold text-[#5f86a5]">{height}%</span><div className={`w-full max-w-[44px] rounded-t-lg ${i === 5 ? 'bg-[#2e75c7]' : 'bg-[#cce7f8]'}`} style={{ height: `${height}%` }} /><span className="text-[10px] font-medium text-[#93a8ba]">{['May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct'][i]}</span></div>)}</div></div><div className="rounded-[22px] bg-[#2776c8] p-6 text-white shadow-[0_16px_35px_rgba(39,118,200,0.2)]"><p className="text-xs font-medium text-[#b9ddfa]">This month</p><p className="mt-3 text-[36px] font-bold tracking-[-0.05em]">94%</p><p className="mt-1 text-xs text-[#c4e2f8]">Best attendance this year</p><div className="mt-8 space-y-3"><div className="flex justify-between text-xs text-[#c4e2f8]"><span>Present</span><span>45 members</span></div><div className="h-2 rounded-full bg-white/20"><div className="h-2 w-[94%] rounded-full bg-white" /></div><div className="flex justify-between text-xs text-[#c4e2f8]"><span>Absent or late</span><span>3 members</span></div></div></div></section>
      <section className="mt-6 rounded-[22px] border border-[#dce8f3] bg-white p-5 shadow-[0_12px_36px_rgba(49,92,130,0.05)] sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-bold text-[#1a3858]">Meeting attendance</h2><p className="mt-1 text-xs text-[#89a0b6]">Recent family gatherings and participation</p></div><button className="flex items-center gap-1 rounded-lg border border-[#dce8f3] px-2.5 py-2 text-xs font-medium text-[#58738f]">All meetings <ChevronDown className="size-3.5" /></button></div><div className="mt-5 grid gap-3">{sessions.map((session) => <div key={session.title} className="flex flex-col gap-3 rounded-2xl border border-[#e7eff6] p-3.5 sm:flex-row sm:items-center sm:gap-4"><div className="flex size-11 shrink-0 flex-col items-center justify-center rounded-xl bg-[#edf7ff] text-[#2c76c4]"><span className="text-base font-bold leading-none">{session.date}</span><span className="mt-1 text-[9px] font-bold tracking-wider">{session.month}</span></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#274663]">{session.title}</p><p className="mt-1 text-[11px] text-[#8aa0b5]">{session.meta}</p></div><div className="w-full sm:w-[190px]"><div className="mb-1.5 flex justify-between text-[10px] font-medium text-[#7892ab]"><span>{session.present} of {session.total} present</span><span>{Math.round(session.present / session.total * 100)}%</span></div><div className="h-2 rounded-full bg-[#e8f1f7]"><div className="h-2 rounded-full bg-[#4aa0d0]" style={{ width: `${session.present / session.total * 100}%` }} /></div></div><span className={`rounded-full px-2.5 py-1.5 text-[10px] font-semibold ${session.status === 'Upcoming' ? 'bg-[#e9f5ff] text-[#2d78c6]' : 'bg-[#e9f8f0] text-[#2c9565]'}`}>{session.status}</span></div>)}</div></section>
      <section className="mt-6 rounded-[22px] border border-[#dce8f3] bg-white p-5 shadow-[0_12px_36px_rgba(49,92,130,0.05)] sm:p-6"><div><h2 className="text-base font-bold text-[#1a3858]">Member participation</h2><p className="mt-1 text-xs text-[#89a0b6]">Attendance for the latest meeting</p></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead><tr className="border-b border-[#e7eff6] text-[10px] font-semibold uppercase tracking-[0.12em] text-[#91a6b8]"><th className="pb-3 pl-2">Member</th><th className="pb-3">Status</th><th className="pb-3">Attendance</th><th className="pb-3">Last updated</th></tr></thead><tbody>{members.map(([name, initials, status, rate]) => <tr key={name} className="border-b border-[#eef3f7] last:border-0"><td className="py-3 pl-2"><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-full bg-[#d9efff] text-[10px] font-bold text-[#2764a3]">{initials}</div><span className="text-xs font-semibold text-[#355773]">{name}</span></div></td><td className="py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${status === 'Present' ? 'bg-[#e9f8f0] text-[#2c9565]' : status === 'Late' ? 'bg-[#fff6e4] text-[#b47725]' : 'bg-[#f1f4f7] text-[#7790a7]'}`}>{status}</span></td><td className="py-3 text-xs text-[#58738f]">{rate}</td><td className="py-3 text-xs text-[#91a6b8]">Today, 5:30 PM</td></tr>)}</tbody></table></div></section><p className="mt-8 pb-3 text-center text-[11px] text-[#9ab0c3]">Dominion Family · Faithful records platform</p></div></main>
    <style jsx global>{`.nav-link{display:flex;align-items:center;gap:.75rem;border-radius:.75rem;padding:.75rem;color:#a9bfd8;font-size:13px;font-weight:500}.nav-link svg{width:18px;height:18px}.nav-link:hover{background:rgba(255,255,255,.1);color:white}.nav-link.active{background:#2e75c7;color:white;box-shadow:0 8px 18px rgba(46,117,199,.28)}`}</style>
  </div>
}

function Summary({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-[18px] border border-[#dce8f3] bg-white p-5 shadow-[0_10px_30px_rgba(49,92,130,0.04)]"><div className="flex items-center justify-between"><p className="text-xs font-medium text-[#7892ab]">{label}</p><div className="flex size-9 items-center justify-center rounded-xl bg-[#e8f5ff] text-[#2e75c7]"><CalendarDays className="size-[18px]" /></div></div><p className="mt-4 text-[25px] font-bold tracking-[-0.04em] text-[#183654]">{value}</p><p className="mt-1 text-[11px] font-medium text-[#5e9a7d]">{detail}</p></div> }
