'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Bell, CalendarDays, ChevronDown, HeartHandshake, LayoutDashboard, Menu, Plus, Search, Settings, ShieldCheck, Users, X } from 'lucide-react'

const contributions = [
  { member: 'Daniel Adeyemi', initials: 'DA', type: 'Family levy', amount: 'NGN 25,000', date: '18 Oct 2026', status: 'Confirmed', color: 'bg-[#d9efff] text-[#2764a3]' },
  { member: 'Grace Okafor', initials: 'GO', type: 'Monthly welfare', amount: 'NGN 15,000', date: '15 Oct 2026', status: 'Confirmed', color: 'bg-[#e8f8f0] text-[#27845c]' },
  { member: 'Michael Eze', initials: 'ME', type: 'Family levy', amount: 'NGN 25,000', date: '12 Oct 2026', status: 'Confirmed', color: 'bg-[#fff2dc] text-[#b47725]' },
  { member: 'Esther Adebayo', initials: 'EA', type: 'Building fund', amount: 'NGN 50,000', date: '08 Oct 2026', status: 'Pending', color: 'bg-[#f0edff] text-[#735bca]' },
]

export default function ContributionsPage() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [period, setPeriod] = useState('October 2026')
  return <div className="min-h-screen bg-[#f4f8fc] text-[#172a46]">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[256px] flex-col bg-[#132745] px-5 py-6 text-white transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between px-2"><Link href="/" className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-[13px] bg-[#8dd6ff] text-[#132745]"><HeartHandshake className="size-5" /></div><div><p className="text-[15px] font-bold tracking-wide">Faithful</p><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[#8da8c8]">Family records</p></div></Link><button aria-label="Close navigation" className="rounded-lg p-2 text-[#a9bfd8] lg:hidden" onClick={() => setMobileOpen(false)}><X /></button></div>
      <nav className="mt-12 flex flex-1 flex-col gap-1.5" aria-label="Main navigation"><p className="px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#7592b4]">Workspace</p><Link href="/" className="nav-link"><LayoutDashboard />Overview</Link><Link href="/roster" className="nav-link"><Users />Family roster</Link><Link href="/meetings" className="nav-link"><CalendarDays />Meetings &amp; minutes</Link><Link href="/attendance" className="nav-link"><CalendarDays />Attendance</Link><Link href="/contributions" className="nav-link active"><ShieldCheck />Contributions</Link><p className="mt-10 px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#7592b4]">Account</p><Link href="/settings" className="nav-link"><Settings />Settings</Link></nav>
      <div className="rounded-2xl border border-white/10 bg-white/6 p-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-[#d9efff] text-sm font-bold text-[#2764a3]">DA</div><div><p className="text-xs font-semibold">Daniel Adeyemi</p><p className="mt-0.5 text-[11px] text-[#8da8c8]">Member · Dominion</p></div></div></div>
    </aside>{mobileOpen && <button aria-label="Close navigation overlay" className="fixed inset-0 z-20 bg-[#0e2039]/40 lg:hidden" onClick={() => setMobileOpen(false)} />}
    <main className="lg:pl-[256px]"><header className="flex h-[76px] items-center justify-between border-b border-[#dce8f3] bg-white/80 px-5 backdrop-blur-xl sm:px-8 lg:px-10"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="rounded-xl p-2 text-[#426487] lg:hidden" onClick={() => setMobileOpen(true)}><Menu /></button><div className="hidden items-center gap-2 text-xs text-[#7690aa] sm:flex"><span>Family workspace</span><span>/</span><span className="font-medium text-[#274463]">Contributions</span></div><span className="text-sm font-semibold text-[#1f3857] sm:hidden">Contributions</span></div><div className="flex items-center gap-2 sm:gap-4"><button aria-label="Search" className="rounded-xl p-2.5 text-[#55718e]"><Search className="size-[19px]" /></button><button aria-label="Notifications" className="relative rounded-xl p-2.5 text-[#55718e]"><Bell className="size-[19px]" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-[#2f8ad8]" /></button><div className="flex size-8 items-center justify-center rounded-full bg-[#d9efff] text-xs font-bold text-[#2764a3]">DA</div></div></header>
      <div className="mx-auto max-w-[1380px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9"><Link href="/" className="inline-flex items-center gap-2 text-xs font-semibold text-[#5f82a2] hover:text-[#2e75c7]"><ArrowLeft className="size-4" />Back to overview</Link><section className="mt-6 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-medium text-[#5d7b99]">Dominion Family</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em] text-[#142e4d] sm:text-[38px]">Contributions <span className="text-[#4295d5">.</span></h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#7290ad]">Keep a clear, trusted record of how our family gives and supports one another.</p></div><button className="flex w-fit items-center gap-2 rounded-xl bg-[#2e75c7] px-4 py-3 text-sm font-semibold text-white shadow-[0_10px_20px_rgba(46,117,199,0.2)]"><Plus className="size-4" />Record contribution</button></section>
      <section className="mt-8 grid gap-4 sm:grid-cols-3"><Summary label="Total this month" value="NGN 315,000" detail="+12.5% from September" /><Summary label="Family target" value="NGN 500,000" detail="63% reached" /><Summary label="Contributors" value="34 / 48" detail="71% of members" /></section>
      <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(320px,0.8fr)]"><div className="rounded-[22px] border border-[#dce8f3] bg-white p-5 shadow-[0_12px_36px_rgba(49,92,130,0.05)] sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-bold text-[#1a3858]">Giving progress</h2><p className="mt-1 text-xs text-[#89a0b6]">Monthly family contribution target</p></div><select aria-label="Contribution period" value={period} onChange={(event) => setPeriod(event.target.value)} className="rounded-lg border border-[#dce8f3] bg-white px-2.5 py-2 text-xs font-medium text-[#58738f]"><option>October 2026</option><option>September 2026</option><option>August 2026</option></select></div><div className="mt-8 flex items-end justify-between"><div><p className="text-[38px] font-bold tracking-[-0.05em] text-[#183654]">NGN 315,000</p><p className="mt-1 text-xs text-[#89a0b6]">of NGN 500,000 goal</p></div><p className="text-2xl font-bold text-[#2e75c7]">63%</p></div><div className="mt-5 h-3 rounded-full bg-[#e8f1f7]"><div className="h-3 w-[63%] rounded-full bg-[#2e75c7]" /></div><div className="mt-4 flex justify-between text-[11px] text-[#7892ab]"><span>NGN 0</span><span>NGN 185,000 remaining</span><span>NGN 500,000</span></div></div><div className="rounded-[22px] bg-[#2776c8] p-6 text-white shadow-[0_16px_35px_rgba(39,118,200,0.2)]"><p className="text-xs font-medium text-[#b9ddfa]">Your giving</p><p className="mt-3 text-[36px] font-bold tracking-[-0.05em]">NGN 40,000</p><p className="mt-1 text-xs text-[#c4e2f8]">Contributed this month</p><div className="mt-8 flex items-center justify-between border-t border-white/15 pt-4 text-xs"><span className="text-[#c4e2f8]">Next contribution</span><span className="font-semibold">Due 31 Oct</span></div></div></section>
      <section className="mt-6 rounded-[22px] border border-[#dce8f3] bg-white p-5 shadow-[0_12px_36px_rgba(49,92,130,0.05)] sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-base font-bold text-[#1a3858]">Recent contributions</h2><p className="mt-1 text-xs text-[#89a0b6]">A transparent record for the family</p></div><button className="flex items-center gap-1 rounded-lg border border-[#dce8f3] px-2.5 py-2 text-xs font-medium text-[#58738f]">All types <ChevronDown className="size-3.5" /></button></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-[#e7eff6] text-[10px] font-semibold uppercase tracking-[0.12em] text-[#91a6b8]"><th className="pb-3 pl-2">Contributor</th><th className="pb-3">Type</th><th className="pb-3">Amount</th><th className="pb-3">Date</th><th className="pb-3">Status</th></tr></thead><tbody>{contributions.map((item) => <tr key={`${item.member}-${item.date}`} className="border-b border-[#eef3f7] last:border-0"><td className="py-3 pl-2"><div className="flex items-center gap-3"><div className={`flex size-8 items-center justify-center rounded-full text-[10px] font-bold ${item.color}`}>{item.initials}</div><span className="text-xs font-semibold text-[#355773]">{item.member}</span></div></td><td className="py-3 text-xs text-[#58738f]">{item.type}</td><td className="py-3 text-xs font-bold text-[#274663]">{item.amount}</td><td className="py-3 text-xs text-[#91a6b8]">{item.date}</td><td className="py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${item.status === 'Confirmed' ? 'bg-[#e9f8f0] text-[#2c9565]' : 'bg-[#fff6e4] text-[#b47725]'}`}>{item.status}</span></td></tr>)}</tbody></table></div></section><p className="mt-8 pb-3 text-center text-[11px] text-[#9ab0c3]">Dominion Family · Faithful records platform</p></div></main><style jsx global>{`.nav-link{display:flex;align-items:center;gap:.75rem;border-radius:.75rem;padding:.75rem;color:#a9bfd8;font-size:13px;font-weight:500}.nav-link svg{width:18px;height:18px}.nav-link:hover{background:rgba(255,255,255,.1);color:white}.nav-link.active{background:#2e75c7;color:white;box-shadow:0 8px 18px rgba(46,117,199,.28)}`}</style></div>
}

function Summary({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-[18px] border border-[#dce8f3] bg-white p-5 shadow-[0_10px_30px_rgba(49,92,130,0.04)]"><div className="flex items-center justify-between"><p className="text-xs font-medium text-[#7892ab]">{label}</p><div className="flex size-9 items-center justify-center rounded-xl bg-[#e8f5ff] text-[#2e75c7]"><ShieldCheck className="size-[18px]" /></div></div><p className="mt-4 text-[25px] font-bold tracking-[-0.04em] text-[#183654]">{value}</p><p className="mt-1 text-[11px] font-medium text-[#5e9a7d]">{detail}</p></div> }
