'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Bell, CalendarDays, ChevronDown, Download, FileText, HeartHandshake, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Users, X } from 'lucide-react'

const meetings = [
  { date: '24', month: 'OCT', title: 'Family thanksgiving meeting', type: 'General meeting', time: '4:00 PM – 6:00 PM', location: 'Dominion Family Centre', status: 'Upcoming', accent: 'blue' },
  { date: '10', month: 'OCT', title: 'Monthly family meeting', type: 'General meeting', time: '4:00 PM – 5:30 PM', location: 'Online · Google Meet', status: 'Minutes published', accent: 'green' },
  { date: '26', month: 'SEP', title: 'September family meeting', type: 'General meeting', time: '4:00 PM – 5:30 PM', location: 'Dominion Family Centre', status: 'Minutes published', accent: 'slate' },
  { date: '12', month: 'SEP', title: 'Family welfare committee', type: 'Committee meeting', time: '5:00 PM – 6:00 PM', location: 'Online · Google Meet', status: 'Minutes published', accent: 'slate' },
]

const minutes = [
  { title: 'Monthly family meeting', date: '10 October 2026', author: 'Daniel Adeyemi', pages: '4 pages' },
  { title: 'September family meeting', date: '26 September 2026', author: 'Grace Okafor', pages: '6 pages' },
  { title: 'Family welfare committee', date: '12 September 2026', author: 'Michael Eze', pages: '3 pages' },
]

export default function MeetingsMinutes() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [tab, setTab] = useState<'meetings' | 'minutes'>('meetings')
  return <div className="min-h-screen bg-[#f4f8fc] text-[#172a46]">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[256px] flex-col bg-[#132745] px-5 py-6 text-white transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between px-2"><Link href="/" className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-[13px] bg-[#8dd6ff] text-[#132745]"><HeartHandshake className="size-5" /></div><div><p className="text-[15px] font-bold tracking-wide">Faithful</p><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[#8da8c8]">Family records</p></div></Link><button aria-label="Close navigation" className="rounded-lg p-2 text-[#a9bfd8] lg:hidden" onClick={() => setMobileOpen(false)}><X /></button></div>
      <nav className="mt-12 flex flex-1 flex-col gap-1.5" aria-label="Main navigation"><p className="px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#7592b4]">Workspace</p><Link href="/" className="flex items-center gap-3 rounded-xl px-3 py-3 text-[13px] font-medium text-[#a9bfd8] hover:bg-white/10"><LayoutDashboard className="size-[18px]" />Overview</Link><Link href="/roster" className="flex items-center gap-3 rounded-xl px-3 py-3 text-[13px] font-medium text-[#a9bfd8] hover:bg-white/10"><Users className="size-[18px]" />Family roster</Link><Link href="/meetings" className="flex items-center gap-3 rounded-xl bg-[#2e75c7] px-3 py-3 text-[13px] font-medium text-white shadow-[0_8px_18px_rgba(46,117,199,0.28)]"><FileText className="size-[18px]" />Meetings &amp; minutes</Link><Link href="#attendance" className="flex items-center gap-3 rounded-xl px-3 py-3 text-[13px] font-medium text-[#a9bfd8] hover:bg-white/10"><CalendarDays className="size-[18px]" />Attendance</Link><Link href="#contributions" className="flex items-center gap-3 rounded-xl px-3 py-3 text-[13px] font-medium text-[#a9bfd8] hover:bg-white/10"><ShieldCheck className="size-[18px]" />Contributions</Link><p className="mt-10 px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#7592b4]">Account</p><button className="flex items-center gap-3 rounded-xl px-3 py-3 text-left text-[13px] font-medium text-[#a9bfd8] hover:bg-white/10"><Settings className="size-[18px]" />Settings</button></nav>
      <div className="rounded-2xl border border-white/10 bg-white/6 p-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-[#d9efff] text-sm font-bold text-[#2764a3]">DA</div><div><p className="text-xs font-semibold">Daniel Adeyemi</p><p className="mt-0.5 text-[11px] text-[#8da8c8]">Member · Dominion</p></div></div></div>
    </aside>
    {mobileOpen && <button aria-label="Close navigation overlay" className="fixed inset-0 z-20 bg-[#0e2039]/40 lg:hidden" onClick={() => setMobileOpen(false)} />}
    <main className="lg:pl-[256px]"><header className="flex h-[76px] items-center justify-between border-b border-[#dce8f3] bg-white/80 px-5 backdrop-blur-xl sm:px-8 lg:px-10"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="rounded-xl p-2 text-[#426487] lg:hidden" onClick={() => setMobileOpen(true)}><Menu /></button><div className="hidden items-center gap-2 text-xs text-[#7690aa] sm:flex"><span>Family workspace</span><span>/</span><span className="font-medium text-[#274463]">Meetings &amp; minutes</span></div><span className="text-sm font-semibold text-[#1f3857] sm:hidden">Meetings &amp; minutes</span></div><div className="flex items-center gap-2 sm:gap-4"><button aria-label="Search" className="rounded-xl p-2.5 text-[#55718e]"><Search className="size-[19px]" /></button><button aria-label="Notifications" className="relative rounded-xl p-2.5 text-[#55718e]"><Bell className="size-[19px]" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-[#2f8ad8]" /></button><div className="flex size-8 items-center justify-center rounded-full bg-[#d9efff] text-xs font-bold text-[#2764a3]">DA</div></div></header>
      <div className="mx-auto max-w-[1380px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9"><Link href="/" className="inline-flex items-center gap-2 text-xs font-semibold text-[#5f82a2] hover:text-[#2e75c7]"><ArrowLeft className="size-4" />Back to overview</Link><section className="mt-6 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-medium text-[#5d7b99]">Family workspace</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em] text-[#142e4d] sm:text-[38px]">Meetings &amp; minutes <span className="text-[#4295d5]">.</span></h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#7290ad]">Keep up with family decisions, upcoming gatherings, and the records that keep us connected.</p></div><button className="flex w-fit items-center gap-2 rounded-xl bg-[#2e75c7] px-4 py-3 text-sm font-semibold text-white shadow-[0_10px_20px_rgba(46,117,199,0.2)]"><Plus className="size-4" />Schedule meeting</button></section>
        <div className="mt-8 flex items-center justify-between border-b border-[#dce8f3]"><div className="flex gap-6"><button onClick={() => setTab('meetings')} className={`border-b-2 pb-3 text-sm font-semibold ${tab === 'meetings' ? 'border-[#2e75c7] text-[#2e75c7]' : 'border-transparent text-[#7892ab]'}`}>Upcoming meetings</button><button onClick={() => setTab('minutes')} className={`border-b-2 pb-3 text-sm font-semibold ${tab === 'minutes' ? 'border-[#2e75c7] text-[#2e75c7]' : 'border-transparent text-[#7892ab]'}`}>Published minutes <span className="ml-1 rounded-full bg-[#e8f5ff] px-2 py-0.5 text-[10px] text-[#2e75c7]">12</span></button></div><button className="hidden items-center gap-1.5 rounded-lg border border-[#dce8f3] bg-white px-3 py-2 text-xs font-medium text-[#58738f] sm:flex">2026 <ChevronDown className="size-3.5" /></button></div>
        {tab === 'meetings' ? <section className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><div className="flex flex-col gap-3">{meetings.map((meeting) => <MeetingCard key={meeting.title} {...meeting} />)}</div><aside className="h-fit rounded-[22px] bg-[#2776c8] p-6 text-white shadow-[0_16px_35px_rgba(39,118,200,0.2)]"><p className="text-xs font-medium text-[#b9ddfa]">Meeting rhythm</p><p className="mt-3 text-3xl font-bold">Every month</p><p className="mt-2 text-xs leading-5 text-[#c4e2f8]">Regular gatherings help our family stay informed, supported, and close.</p><div className="mt-7 border-t border-white/20 pt-5"><p className="text-[11px] text-[#c4e2f8]">Next gathering</p><p className="mt-1 text-sm font-semibold">24 October 2026</p><p className="mt-1 text-xs text-[#c4e2f8]">Family thanksgiving meeting</p></div></aside></section> : <section className="mt-6 grid gap-3">{minutes.map((minute) => <div key={minute.title} className="flex flex-col gap-4 rounded-[18px] border border-[#dce8f3] bg-white p-5 shadow-[0_10px_30px_rgba(49,92,130,0.04)] sm:flex-row sm:items-center"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-[#e8f5ff] text-[#2e75c7]"><FileText className="size-5" /></div><div className="min-w-0 flex-1"><h2 className="text-sm font-bold text-[#274663]">{minute.title}</h2><p className="mt-1 text-xs text-[#8aa0b5]">{minute.date} · Published by {minute.author} · {minute.pages}</p></div><button className="flex items-center gap-2 text-xs font-semibold text-[#2e75c7]"><Download className="size-4" />Download PDF</button><button aria-label={`More options for ${minute.title}`} className="rounded-lg p-2 text-[#8aa0b5]"><MoreHorizontal className="size-4" /></button></div>)}</section>}
        <p className="mt-10 pb-3 text-center text-[11px] text-[#9ab0c3]">Dominion Family · Faithful records platform</p></div></main>
  </div>
}

function MeetingCard({ date, month, title, type, time, location, status, accent }: { date: string; month: string; title: string; type: string; time: string; location: string; status: string; accent: string }) { return <article className="rounded-[20px] border border-[#dce8f3] bg-white p-5 shadow-[0_10px_30px_rgba(49,92,130,0.04)] transition hover:border-[#b9dbf2] hover:shadow-[0_14px_32px_rgba(49,92,130,0.08)]"><div className="flex items-start gap-4"><div className={`flex size-[58px] shrink-0 flex-col items-center justify-center rounded-2xl ${accent === 'blue' ? 'bg-[#e8f5ff] text-[#2e75c7]' : 'bg-[#f1f4f7] text-[#7790a7]'}`}><span className="text-xl font-bold leading-none">{date}</span><span className="mt-1 text-[9px] font-bold tracking-wider">{month}</span></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-base font-bold text-[#274663]">{title}</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${status === 'Upcoming' ? 'bg-[#e9f5ff] text-[#2d78c6]' : 'bg-[#e9f8f0] text-[#2c9565]'}`}>{status}</span></div><p className="mt-1 text-xs text-[#8aa0b5]">{type}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#66829d]"><span className="flex items-center gap-1.5"><CalendarDays className="size-3.5 text-[#66a8d7]" />{time}</span><span>{location}</span></div></div><button aria-label={`More options for ${title}`} className="rounded-lg p-2 text-[#8aa0b5]"><MoreHorizontal className="size-5" /></button></div></article> }
