'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Bell, CalendarDays, Check, HeartHandshake, LayoutDashboard, Menu, Search, Settings, ShieldCheck, SlidersHorizontal, Users, X } from 'lucide-react'

const users = [
  ['Daniel Adeyemi', 'DA', 'Family coordinator', 'Administrator', 'Active'],
  ['Grace Okafor', 'GO', 'Secretary', 'Manager', 'Active'],
  ['Michael Eze', 'ME', 'Welfare lead', 'Editor', 'Active'],
]

export default function SettingsPage() {
  const [mobileOpen, setMobileOpen] = useState(false)
  const [section, setSection] = useState('User management')
  const [saved, setSaved] = useState(false)
  const [notifications, setNotifications] = useState(true)
  const sections = ['User management', 'System management', 'Profile & security']
  return <div className="min-h-screen bg-[#f4f8fc] text-[#172a46]">
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[256px] flex-col bg-[#132745] px-5 py-6 text-white transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between px-2"><Link href="/" className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-[13px] bg-[#8dd6ff] text-[#132745]"><HeartHandshake className="size-5" /></div><div><p className="text-[15px] font-bold tracking-wide">Faithful</p><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[#8da8c8]">Family records</p></div></Link><button aria-label="Close navigation" className="rounded-lg p-2 text-[#a9bfd8] lg:hidden" onClick={() => setMobileOpen(false)}><X /></button></div><nav className="mt-12 flex flex-1 flex-col gap-1.5" aria-label="Main navigation"><p className="px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#7592b4]">Workspace</p><Link href="/" className="nav-link"><LayoutDashboard />Overview</Link><Link href="/roster" className="nav-link"><Users />Family roster</Link><Link href="/meetings" className="nav-link"><CalendarDays />Meetings &amp; minutes</Link><Link href="/attendance" className="nav-link"><CalendarDays />Attendance</Link><Link href="/contributions" className="nav-link"><ShieldCheck />Contributions</Link><p className="mt-10 px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-[#7592b4]">Account</p><Link href="/settings" className="nav-link active"><Settings />Settings</Link></nav><div className="rounded-2xl border border-white/10 bg-white/6 p-4"><div className="flex items-center gap-3"><div className="flex size-9 items-center justify-center rounded-full bg-[#d9efff] text-sm font-bold text-[#2764a3]">DA</div><div><p className="text-xs font-semibold">Daniel Adeyemi</p><p className="mt-0.5 text-[11px] text-[#8da8c8]">Member · Dominion</p></div></div></div></aside>{mobileOpen && <button aria-label="Close navigation overlay" className="fixed inset-0 z-20 bg-[#0e2039]/40 lg:hidden" onClick={() => setMobileOpen(false)} />}
    <main className="lg:pl-[256px]"><header className="flex h-[76px] items-center justify-between border-b border-[#dce8f3] bg-white/80 px-5 backdrop-blur-xl sm:px-8 lg:px-10"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="rounded-xl p-2 text-[#426487] lg:hidden" onClick={() => setMobileOpen(true)}><Menu /></button><div className="hidden items-center gap-2 text-xs text-[#7690aa] sm:flex"><span>Family workspace</span><span>/</span><span className="font-medium text-[#274463]">Settings</span></div><span className="text-sm font-semibold text-[#1f3857] sm:hidden">Settings</span></div><div className="flex items-center gap-2 sm:gap-4"><button aria-label="Search" className="rounded-xl p-2.5 text-[#55718e]"><Search className="size-[19px]" /></button><button aria-label="Notifications" className="relative rounded-xl p-2.5 text-[#55718e]"><Bell className="size-[19px]" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-[#2f8ad8]" /></button><div className="flex size-8 items-center justify-center rounded-full bg-[#d9efff] text-xs font-bold text-[#2764a3]">DA</div></div></header>
      <div className="mx-auto max-w-[1180px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9"><Link href="/" className="inline-flex items-center gap-2 text-xs font-semibold text-[#5f82a2] hover:text-[#2e75c7]"><ArrowLeft className="size-4" />Back to overview</Link><div className="mt-6"><p className="text-sm font-medium text-[#5d7b99]">Dominion Family</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em] text-[#142e4d] sm:text-[38px]">Settings <span className="text-[#4295d5">.</span></h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#7290ad]">Manage who can access your family records and how the workspace operates.</p></div>
      <div className="mt-8 grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><nav className="flex gap-2 overflow-x-auto lg:flex-col" aria-label="Settings sections">{sections.map((item) => <button key={item} onClick={() => setSection(item)} className={`whitespace-nowrap rounded-xl px-4 py-3 text-left text-xs font-semibold transition-colors ${section === item ? 'bg-[#e3f2fd] text-[#2e75c7]' : 'text-[#7390aa] hover:bg-white'}`}>{item}</button>)}</nav><div className="rounded-[22px] border border-[#dce8f3] bg-white p-5 shadow-[0_12px_36px_rgba(49,92,130,0.05)] sm:p-7">{section === 'User management' && <UserManagement />}{section === 'System management' && <SystemManagement notifications={notifications} setNotifications={setNotifications} />}{section === 'Profile & security' && <ProfileSecurity />}{section !== 'Profile & security' && <div className="mt-7 flex justify-end border-t border-[#e7eff6] pt-5"><button onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 2200) }} className="flex items-center gap-2 rounded-xl bg-[#2e75c7] px-4 py-3 text-xs font-semibold text-white shadow-[0_10px_20px_rgba(46,117,199,0.2)]">{saved && <Check className="size-4" />}{saved ? 'Changes saved' : 'Save changes'}</button></div>}</div></div><p className="mt-8 pb-3 text-center text-[11px] text-[#9ab0c3]">Dominion Family · Faithful records platform</p></div></main><style jsx global>{`.nav-link{display:flex;align-items:center;gap:.75rem;border-radius:.75rem;padding:.75rem;color:#a9bfd8;font-size:13px;font-weight:500}.nav-link svg{width:18px;height:18px}.nav-link:hover{background:rgba(255,255,255,.1);color:white}.nav-link.active{background:#2e75c7;color:white;box-shadow:0 8px 18px rgba(46,117,199,.28)}`}</style></div>
}

function UserManagement() { return <div><Heading title="User management" text="Invite members, assign roles, and control access to the family workspace." action="Invite user" /><div className="mt-6 grid gap-3 sm:grid-cols-3"><Stat label="48" text="Total users" /><Stat label="46" text="Active" /><Stat label="2" text="Pending invites" /></div><div className="mt-7 overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead><tr className="border-b border-[#e7eff6] text-[10px] uppercase tracking-[0.12em] text-[#91a6b8]"><th className="pb-3 pl-2">User</th><th className="pb-3">Role</th><th className="pb-3">Access</th><th className="pb-3">Status</th></tr></thead><tbody>{users.map(([name, initials, role, access, status]) => <tr key={name} className="border-b border-[#eef3f7] last:border-0"><td className="py-3 pl-2"><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-full bg-[#d9efff] text-[10px] font-bold text-[#2764a3]">{initials}</div><span className="text-xs font-semibold text-[#355773]">{name}</span></div></td><td className="py-3 text-xs text-[#58738f]">{role}</td><td className="py-3"><span className="rounded-full bg-[#edf7ff] px-2.5 py-1 text-[10px] font-semibold text-[#2e75c7]">{access}</span></td><td className="py-3 text-xs text-[#2c9565]">{status}</td></tr>)}</tbody></table></div></div> }

function SystemManagement({ notifications, setNotifications }: { notifications: boolean; setNotifications: (value: boolean) => void }) { return <div><Heading title="System management" text="Configure defaults, notifications, and the way your family workspace behaves." action="" /><div className="mt-7 flex flex-col gap-4"><SettingRow title="Family name" text="The name shown across your workspace" control={<input defaultValue="Dominion Family" className="w-full rounded-xl border border-[#dce8f3] px-3 py-2 text-xs text-[#355773] outline-none focus:border-[#75b6e5] sm:w-56" />} /><SettingRow title="Default branch" text="Used when adding new members" control={<select defaultValue="Central branch" className="rounded-xl border border-[#dce8f3] px-3 py-2 text-xs text-[#355773] outline-none"><option>Central branch</option><option>North branch</option><option>East branch</option></select>} /><SettingRow title="Meeting reminders" text="Notify members before scheduled meetings" control={<Toggle checked={notifications} onClick={() => setNotifications(!notifications)} />} /><SettingRow title="Require approval for records" text="Review new members and contributions before publishing" control={<Toggle checked={true} onClick={() => {}} />} /></div></div> }

function ProfileSecurity() { return <div><Heading title="Profile & security" text="Keep your account details and access secure." action="" /><div className="mt-7 grid gap-4 sm:grid-cols-2"><Field label="Full name" value="Daniel Adeyemi" /><Field label="Email address" value="daniel@dominionfamily.org" /><Field label="Phone number" value="+234 803 421 7784" /><Field label="Role" value="Family coordinator" /></div><div className="mt-7 rounded-2xl border border-[#e7eff6] bg-[#fafdff] p-4"><p className="text-sm font-semibold text-[#274663]">Password &amp; sign-in</p><p className="mt-1 text-xs text-[#89a0b6]">Your password was last updated 3 months ago.</p><button className="mt-4 rounded-xl border border-[#cfe0ed] px-3 py-2 text-xs font-semibold text-[#426987]">Change password</button></div></div> }

function Heading({ title, text, action }: { title: string; text: string; action: string }) { return <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="text-lg font-bold text-[#1a3858]">{title}</h2><p className="mt-1 max-w-lg text-xs leading-5 text-[#89a0b6]">{text}</p></div>{action && <button className="flex w-fit items-center gap-2 rounded-xl bg-[#2e75c7] px-3.5 py-2.5 text-xs font-semibold text-white"><Users className="size-4" />{action}</button>}</div> }
function Stat({ label, text }: { label: string; text: string }) { return <div className="rounded-xl bg-[#f4f9fd] p-4"><p className="text-xl font-bold text-[#183654]">{label}</p><p className="mt-1 text-[11px] text-[#7892ab]">{text}</p></div> }
function SettingRow({ title, text, control }: { title: string; text: string; control: React.ReactNode }) { return <div className="flex flex-col justify-between gap-3 rounded-2xl border border-[#e7eff6] p-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-[#355773]">{title}</p><p className="mt-1 text-xs text-[#89a0b6]">{text}</p></div>{control}</div> }
function Toggle({ checked, onClick }: { checked: boolean; onClick: () => void }) { return <button aria-label="Toggle setting" aria-pressed={checked} onClick={onClick} className={`flex h-6 w-11 rounded-full p-1 transition-colors ${checked ? 'justify-end bg-[#2e75c7]' : 'justify-start bg-[#cbdbe8]'}`}><span className="size-4 rounded-full bg-white shadow-sm" /></button> }
function Field({ label, value }: { label: string; value: string }) { return <label className="flex flex-col gap-2"><span className="text-xs font-semibold text-[#58738f]">{label}</span><input defaultValue={value} className="rounded-xl border border-[#dce8f3] px-3 py-2.5 text-xs text-[#355773] outline-none focus:border-[#75b6e5]" /></label> }
